Ciencia de Datos en Python

Universidad Galileo

Nombre: Marco Vinicio Escalante Lara

Carnet: **19001148**


# Investigación: np.matrix vs np.ndarray

Las matrices en Numpy son bidimensionales (2 dimensiones), mientras que los arrays son de N dimensiones.

Esto quiere decir que las matrices están contenidas en los arreglos, y una matriz no es nada más que un arreglo de dos dimensiones, la matriz toma los atributos y metodos de los arreglos. Sin embargo al ser la matriz muy utilizada se añadieron otras operaciones especificas a la misma que permiten facilitar la operación al usuario final.

In [2]:
import numpy as np

# Principales diferencias

La principal diferencia entre los arreglos y las matrices radica en la multiplicación, permitiendo una notación que facilita la multiplicación de dos matrices.

Para multiplicar dos matrices A y B tenemos que utilizar el operador *"*"* para ejecutar la misma, esto quiere decir que la multiplicación quedaria como A * B. Ver ejemplo:

In [19]:
A=np.mat('1 5; 1 8') # Matriz A
B=np.mat('5 2; 4 7') # Matriz B

print(A)
print(B)

print("La multiplicación de la matriz A por la matriz B es:")
print(A*B)

[[1 5]
 [1 8]]
[[5 2]
 [4 7]]
La multiplicación de la matriz A por la matriz B es:
[[25 37]
 [37 58]]


Para multiplicar dos arreglos A y B, no es igual que matrices usando el operador *"*"* sino que hay que utilizar el operador "@", esto a partir de Pyton 3.5. Ver ejemplo:

In [20]:
A1 = np.array([[1, 5], [1, 8]])
B1 = np.array([[5, 2], [4, 7]])


print(A1)
print(B1)

print("Si uno utiliza la notación de matriz *, se obtiene el siguiente resultado:")
print(A1*B1)

print("La multiplicación de la matriz A por la matriz B es:")
print(A1 @ B1)

[[1 5]
 [1 8]]
[[5 2]
 [4 7]]
Si uno utiliza la notación de matriz *, se obtiene el siguiente resultado:
[[ 5 10]
 [ 4 56]]
La multiplicación de la matriz A por la matriz B es:
[[25 37]
 [37 58]]


Como se puede apreciar en el ejemplo, si uno utiliza la misma notación de multiplicación en matrices A1 * B1, el resultado que se obtiene es multiplicar ambas matrices elemento por elemento, mientras que si se utiliza A1 @ B1, el resultado es el mismo que utilizando matrices.

Utilizando operadores **:

Al realizar la operación "A ** 2" en matrices devuleve la multiplicación de la matriz A por la matriz A, mientras que con los arreglos la operación "A1 ** 2" devuleve cada elemento de la matriz elevado al cuadrado, como se puede apreciar en los siguientes ejemplos: 

In [21]:
print("Matriz A:")
print(A)

print("Arreglo A:")
print(A1)

print("Resultado de A**2, para matriz:")
print(A**2)

print("Resultado de A1**2, para arreglo:")
print(A1**2)

Matriz A:
[[1 5]
 [1 8]]
Arreglo A:
[[1 5]
 [1 8]]
Resultado de A**2, para matriz:
[[ 6 45]
 [ 9 69]]
Resultado de A1**2, para arreglo:
[[ 1 25]
 [ 1 64]]


Propiedades Especificas de matrices:

Entre las propiedades especificas de las matrices se encuentran:
1. Poder determinar la matriz identidad, identificada por la letra I.
2. El resto de operaciones que se utilizan en matrices tales como la transpuesta, multiplicación de escalares, suma de las mismas, se operan identicamente.

## Conclusión

Para fines practicas, si solo trabajaremos con dos dimensiones es recomendable utilizar matrices, sin embargo si ya vamos a trabajar con más dimensiones no se puede utilizar matrices si no que arreglos.