28/03/2019

**Universidad Galileo**

Ciencia de Datos en Python

**Nombre:** Marco Vinicio Escalante Lara

**Carnet:** 19001148

## Ejercicio practico: multiplicacion y aritmetica matricial

In [1]:
import numpy as np

### Función de Bellman

In [2]:
V = np.array([0,0,0]) # valor inicial de V(s)
R = np.array([10,2,5]) # vector de recompensas
P = np.array([[0.5,0.25,0.25],
              [0.2,0.40,0.40],
              [0.80,0.10,0.10]])  # matriz de transición
gamma = 0.99
def funcion_bellman(V):
    V= R + gamma*np.matmul(V,P)
    return V

funcion_bellman(V)

array([10.,  2.,  5.])

### Red Neuronal No. 1

Red neuronal utilizando en la capa intermedia y de salida la función sigmoidal

In [3]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [4]:
X = np.array([1, 1])

def red_neuronal(X):
    HL_W1 = np.array([[0.712, 0.355, 0.268], 
                      [0.112, 0.855, 0.468]])
    OL_W1 = np.array([[0.116],
                      [0.329], 
                      [0.708]])
    H1 = np.matmul(X,HL_W1)
    H1 = sigmoid(H1)
    OL = np.matmul(H1, OL_W1)
    return sigmoid(OL)
    

X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

red_neuronal(X)

array([[0.70244573],
       [0.66259284],
       [0.75933678],
       [0.75973948],
       [0.75802295],
       [0.6739704 ],
       [0.75954693],
       [0.76005845],
       [0.75952743],
       [0.76005845]])

### Red Neuronal No. 2 (Final)

Red neuronal utilizando en la capa intermedia la función sigmoidal y en la salida la función propuesta.

In [5]:
def red_neuronal2(X):
    HL_W1 = np.array([[0.712, 0.355, 0.268], 
                      [0.112, 0.855, 0.468]])
    OL_W1 = np.array([[0.116],
                      [0.329], 
                      [0.708]])
    H1 = np.matmul(X,HL_W1)
    H1 = sigmoid(H1)
    OL = np.matmul(H1, OL_W1)
    return np.maximum(OL, 0)
    

X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

red_neuronal2(X)

array([[0.85897151],
       [0.6748703 ],
       [1.14904686],
       [1.15125178],
       [1.14187076],
       [0.72619803],
       [1.15019715],
       [1.153     ],
       [1.1500904 ],
       [1.153     ]])